<a href="https://colab.research.google.com/github/tareq-stonybrook/datasci1_loading/blob/main/loaded_file_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pima Indan DIabeti Database**

*this is a database for diabetic patients*

*This database looks at whether a patient has diabetes, based on 8 body measurements. It covers 768 adult women of Pima Indian heritage.*

Pregnancies - Number of times pregnant.

Glucose - Blood sugar level 2 hours into an oral glucose tolerance test.

BloodPressure - Diastolic blood pressure in mm Hg.

SkinThickness - Triceps skin fold thickness in mm.

Insulin - Blood insulin level 2 hours after the glucose test.

BMI - Body mass index, weight in kg divided by height in meters squared.

DiabetesPedigreeFunction - Score of family history of diabetes.

Age - Age in years.

Outcome - Diabetes status, 1 means diabetes and 0 means no diabetes.

In [3]:
import pandas as pd

db1_csv=('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')
db1=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')
db1.head(11)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0

**Breast Cancer Wisconsin Database**

This database looks at whether a breast tumor is benign or malignant, based on 9 cell measurements. It covers 699 samples.

Id - Sample code number.

Cl.thickness - Clump thickness, scored 1 to 10.

Cell.size - Uniformity of cell size, scored 1 to 10.

Cell.shape - Uniformity of cell shape, scored 1 to 10.

Marg.adhesion - Marginal adhesion, scored 1 to 10.

Epith.c.size - Single epithelial cell size, scored 1 to 10.

Bare.nuclei - Bare nuclei, scored 1 to 10.

Bl.cromatin - Bland chromatin, scored 1 to 10.

Normal.nucleoli - Normal nucleoli, scored 1 to 10.

Mitoses - Mitoses, scored 1 to 10.

Class - Diagnosis, 0 means benign and 1 means malignant.

In [4]:
import pandas as pd

db2_breast_cancer=('https://raw.githubusercontent.com/selva86/datasets/master/BreastCancer.csv' )
db2_breast_cancer=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BreastCancer.csv')
db2_breast_cancer.head(11)

,Id,Cl.thickness,Cell.size,Cell.shape,Marg.adhesion,Epith.c.size,Bare.nuclei,Bl.cromatin,Normal.nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1.0,3,1,1,0
1,1002945,5,4,4,5,7,10.0,3,2,1,0
2,1015425,3,1,1,1,2,2.0,3,1,1,0
3,1016277,6,8,8,1,3,4.0,3,7,1,0
4,1017023,4,1,1,3,2,1.0,3,1,1,0
5,1017122,8,10,10,8,7,10.0,9,7,1,1
6,1018099,1,1,1,1,2,10.0,3,1,1,0
7,1018561,2,1,2,1,2,1.0,3,1,1,0
8,1033078,2,1,1,1,2,1.0,1,1,5,0
9,1033078,4,2,1,1,2,1.0,2,1,1,0
10,1035283,1,1,1,1,1,1.0,3,1,1,0